sudo: required

serveces: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose ecec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose ecec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose ecec --env 'RAILS_ENV=test' web rails test